#!/usr/bin/env python

import os

import sys

env = os.environ.get
src_path = env('APP_SRC_PATH')
command = ''
os.chdir(src_path)

try:
    command = sys.argv[1]
except IndexError:
    print('error: Command missing')
    os._exit(1)

if command == 'app':
    if sys.argv[2] == 'start':
        app_js = [f for f in os.listdir(src_path) if f.startswith('main.') and f.endswith('.js')][0]
        app_js = src_path + '/%s' % app_js
        env_vars = [var for var in os.environ.keys() if var.startswith('APP_')]
        env_vars = {var: env(var) for var in env_vars}

        with open(app_js, 'r+') as f:
            content = f.read()
            for k, v in env_vars.items():
                content = content.replace('@@' + k, v)
            f.seek(0)
            f.write(content)
            f.truncate()

        os.execvp('nginx', ['nginx', '-c', '/etc/nginx/nginx.conf'])
    else:
        print('error: Invalid sub-command')
else:
    os.execvp(sys.argv[1:][0], sys.argv[1:])
